[package]
name = "log_tee"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zstd = "0.13"
libc = "0.2"

[dev-dependencies]
assert_matches = "1.5"
